version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_ROOT_USERNAME=admin
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  my-app:
    image: 630035608091.dkr.ecr.us-east-1.amazonaws.com/my-app:0.2
    ports:
      - 5000:5000
volumes:
  mongo-data:
    driver: local
    
